[package]
name = "strawberry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plex = "0.2.5"
lalrpop-util = "0.17.2"
regex = "0.2.0"
llvm-sys = "140.0.5"

[build-dependencies]
lalrpop = "0.17.2"