// this is a comment.

class Main inherits A{
    b : Int = 0;
    // a : Bool = true;

    function main(ii:Int) -> Int {
        let s:String = "hello";
        let t:Int = 0;
        let flag :Bool= true;
        t = 1;
        t.print_str(s);
        self.print_int(1);
        print_int(1 + 0);
        if(flag) then {
            print_int(1);
            print_int(1);
        }else{
            print_int(0);
        }
        while(true){
            print_int(1);
        }
        return new Int;
    };

    function funa(a:Int) -> Int{
        
    };
};

class A {
    a:Int = 0;
    fun funa(a:Int) -> Int{
        let i:Int = 0;
        let flag :Bool= true;
        while(flag)
        {
             let flag:Int = 0;
            print_int(flag);
        }
        return 0;
    };
};
