// this is a comment.

class Main {
    a : Int = 0;

    function main(ii:Int) -> Int {
        let t:String = "hello";
        let t:Int = 0;
        t = 1;
        t.println(1,2);
        if t then {
            t.println(1);
        } 
        else {  
             t.println(0);
        }
        t.println(1);
        while t {
            t.parse();
        }
    };

    function test() -> Int {
    };
};

