// this is a comment.

class Main inherits A{
    b : Int = 0;

    function main(ii:Int) -> Int {
        let s:String = "hello";
        let t:Int = 0;
        t = 1;
        t.print(1,t + t * t);
        if (t <= 1) then {
            t.print(1);
        } 
        else{
             t.print(0);
        }
        t.print(1);
        while (1 + 2 +3 *4) {
            t.parse();
        }   
        return 0;
    };

    function funa(a:Int) -> Int{
        
    };
};

class A {
    a:Int = 0;
    fun funa(a:Int) -> Int{
        
    };
};
